Repository 2024-TourismContest/Yaguhang_FE, pull requests merged in 2024-09, with the labels that each got.

#47 fix: build에러 수정
  src/components/detail/Category.tsx
  src/components/detail/Review.tsx
  src/pages/detail/DetailPage.tsx
Labels: 🐞 BugFix

#42 feat: 구장근처 관광지 지도로 보기 페이지 기능 개발 (#35,#41)
  src/Router.tsx
  src/apis/main/index.ts
  src/apis/map/index.ts
  src/apis/stadium/index.ts
  src/assets/images/defaltImg.svg
  src/assets/images/loadingImg.svg
  src/components/home/imageSlider.tsx
  src/components/map/BookMarkIcon.tsx
  src/components/map/MapPosition.tsx
  src/components/map/SelectedPosition.tsx
  src/components/map/map.tsx
  src/components/map/useMap.ts
  src/components/stadium/Category.tsx
  src/pages/home/HomePage.tsx
  src/pages/map/mapPage.tsx
  src/pages/stadium/stadiumPage.tsx
  src/store/MapPositionStore.ts
  src/store/MapPositionsStore.ts
Labels: 🐞 BugFix, ✨ Feature, 🎨 Html&css, 📬 API

#46 Feat: 카카오 로그인 기능 구현(#39)
  src/Router.tsx
  src/components/layout/Header.tsx
  src/components/users/LoginForm.tsx
  src/pages/login/LoginPage.tsx
Labels: ✨ Feature, 🎨 Html&css, 📬 API

#56 [Fix]: 상세페이지로 넘어가기 에러수정
  src/components/home/Card.tsx
  src/pages/stadium/stadiumPage.tsx
Labels: 🐞 BugFix

#59 [FEAT] 소셜로그인 공유 구현
  index.html
  src/assets/icons/네이버밴드.png
  src/assets/icons/카카오톡.png
  src/assets/icons/페이스북.png
  src/components/detail/DetailGrid.tsx
  src/components/detail/Share.tsx
  src/pages/detail/DetailPage.tsx
  src/store/ShareStore.ts
  src/types/global.d.ts
Labels: ✨ Feature, 🎨 Html&css, :sparkles: Chore

#73 [FEAT] 컴포넌트 반응형 구현/디테일페이지로 이동 에러 fix
  public/vite.svg
  src/assets/images/Detailnull.svg
  src/assets/images/defaultImg.svg
  src/components/detail/DetailGrid.tsx
  src/components/detail/HeaderImg.tsx
  src/components/detail/MenuContainer.tsx
  src/components/detail/MoreImage.tsx
  src/components/detail/Review.tsx
  src/components/detail/Share.tsx
  src/components/detail/SimilarSpots.tsx
  src/components/home/Card.tsx
  src/components/home/imageSlider.tsx
  src/pages/detail/DetailPage.tsx
  src/pages/home/HomePage.tsx
  src/pages/stadium/stadiumPage.tsx
Labels: 🐞 BugFix, 🎨 Html&css

#76 [FEAT] 리뷰 api통신 및 각종 버그 수정
  src/apis/review/index.ts
  src/components/Review/Review.tsx
  src/components/Review/ReviewForm.tsx
  src/components/Review/ReviewList.tsx
  src/components/detail/Review.tsx
  src/components/detail/SimilarSpots.tsx
  src/pages/detail/DetailPage.tsx
Labels: 🐞 BugFix, ✨ Feature, 🎨 Html&css, 📬 API

#80 [FEAT] 추천행 목차 및 상세 (#66)
  public/reset.css
  src/apis/recommend/index.ts
  src/assets/icons/DialogOpenButton.tsx
  src/assets/icons/heart.tsx
  src/assets/images/DefaultCircle.svg
  src/assets/images/filterAll.svg
  src/assets/images/recommendTitle.svg
  src/components/button/Button.tsx
  src/components/recommend/Item.tsx
  src/components/recommend/RecommendDetail.tsx
  src/components/recommend/filter.tsx
  src/components/recommend/pagenation.tsx
  src/components/recommend/recommendLikeButton.tsx
  src/pages/recommend/RecommendPage.tsx
  src/types/recommendType.ts
Labels: ✨ Feature, 🎨 Html&css, 📬 API

#84 Bug: 날씨 정보 null값 처리하기(#63)
  src/apis/main/index.ts
  src/components/home/WeatherCard.tsx
  src/components/home/WeatherGraph.tsx
Labels: 🐞 BugFix

#82 Feat: 마이페이지 마크업 (#71)
  src/Router.tsx
  src/assets/data/ dummyData.tsx
  src/assets/icons/heart-fill.png
  src/assets/icons/heart-unfill.png
  src/assets/icons/plus.svg
  src/assets/icons/star-fill.png
  src/assets/icons/star-half.png
  src/assets/icons/star-unfill.png
  src/assets/images/arrow.svg
  src/assets/images/default-profile.svg
  src/assets/images/defult-profile.jpg
  src/components/Review/ReviewItem.tsx
  src/components/common/Modal.tsx
  src/components/common/ProfileComponent.tsx
  src/components/common/SectionTitle.tsx
  src/components/layout/Header.tsx
  src/components/layout/MenuItem.tsx
  src/components/myPage/BookMarkList.tsx
  src/components/myPage/GameCard.tsx
  src/components/myPage/GameCardList.tsx
  src/components/myPage/TeamSelector.tsx
  src/components/profile/ProfileEditSection.tsx
  src/components/users/SignupForm.tsx
  src/pages/ myPage/MyAccount.tsx
  src/pages/ myPage/MyBookMark.tsx
  src/pages/ myPage/MyPageLayout.tsx
  src/pages/ myPage/MyPageMain.tsx
  src/pages/ myPage/MyRecommend.tsx
  src/pages/ myPage/MyReview.tsx
  src/pages/ myPage/MyStamp.tsx
  src/pages/home/TitleSection.tsx
  src/pages/profile/ProfilePage.tsx
  src/store/PreferTeamStore.ts
Labels: ✨ Feature, 🎨 Html&css

#89 feat 로그인 시 구단 선택 관련 모달 띄우기(#88)
  src/apis/main/index.ts
  src/components/common/Modal.tsx
  src/components/users/LoginForm.tsx
  src/components/users/SignupForm.tsx
  src/pages/home/HomePage.tsx
Labels: 🐞 BugFix, ✨ Feature

#90 [Feat] 추천행 코스만들기 페이지
  src/Router.tsx
  src/apis/recommend/index.ts
  src/components/button/Button.tsx
  src/components/mycourse/CreateCourse.tsx
  src/components/mycourse/User.tsx
  src/components/recommend/Item.tsx
  src/components/recommend/filter.tsx
  src/pages/mycourse/MycoursePage.tsx
  src/pages/recommend/RecommendPage.tsx
Labels: ✨ Feature, 🎨 Html&css, 📬 API

#100 [FEAT] 각종 스타일 및 버그 수정
  package.json
  src/components/Review/Review.tsx
  src/components/detail/DetailGrid.tsx
  src/components/detail/MoreImage.tsx
  src/components/detail/Share.tsx
  src/components/detail/SimilarSpots.tsx
  src/components/home/Card.tsx
  src/components/layout/Header.tsx
  src/components/mycourse/User.tsx
  src/pages/detail/DetailPage.tsx
  src/pages/myPage/MyStamp.tsx
  src/pages/stadium/TitleSection.tsx
  yarn.lock
Labels: 🐞 BugFix, 🎨 Html&css
